### ISSUE TITLE
Binding a surface to a macOS context doesn't update the GL_FRAMEBUFFER binding

### ISSUE THREAD

**Issue by asajeffrey** [pcwalton/surfman#36] opened 2019-11-14 00:16 UTC
On macOS, if you bind a surface to a context, this doesn't update the binding to GL_FRAMEBUFFER. This produces different behaviour from platforms where binding a surace always uses fbo `0`.

**Comment by asajeffrey** [comment] 2019-11-14 00:17
IRC conversation around an issue in servo that was caused by this: https://mozilla.logbot.info/servo/20191113#c16759025

**Comment by pcwalton** [comment] 2019-11-14 00:19
This is intended behavior. `surfman` tries not to adjust GL state behind your back.

**Comment by pcwalton** [comment] 2019-12-12 05:34
I thought about this more, and the problem with fixing this in surfman 0.2 is that we would need a flag to distinguish between the cases of (a) the current framebuffer at the time of binding a new surface is some previous surface or (b) the current framebuffer at the time of binding a new surface is some user-created FBO. In the former case, we would want to rebind the framebuffers; in the latter case, we would not want to do this. This is technically doable, but it seems inelegant, because it introduces a new piece of state to the context: a "surface was previously bound" flag. I don't see any other way to correctly distinguish the two cases without adding this extra piece of state.

Because of this problem, I'm closing this issue. Feel free to reopen, though, if this functionality is important.

**Closed by pcwalton** 2019-12-12 05:34 UTC
